version: "3"
services:
  mysql:
    image: mysql:8.0.29
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reversi
      MYSQL_USER: reversi
      MYSQL_PASSWORD: password
